bibentry(bibtype = "Article",
         key = "Barthelemy+Monjardet:1981",
         title = "The Median Procedure in Cluster Analysis and Social Choice Theory",
         volume = "1",
         .issn = "0165-4896",
         doi = "10.1016/0165-4896(81)90041-x",
         number = "3",
         journal = "Mathematical Social Sciences",
         publisher = "Elsevier BV",
         author = c(person(given = c("Jean", "Pierre"),
                           family = "Barthélemy"),
                    person(given = "Bernard",
                           family = "Monjardet")),
         year = "1981",
         month = "may",
pages = "235--267")

bibentry(bibtype = "Misc",
         key = "Borda:1781",
         author = person(given = c("J.", "C."),
                         family = "Borda"),
         title = "M{\\'e}moire sur les {\\'e}lections au scrutin",
         howpublished = "Histoire de l'Acad{\\'e}mie Royale des Sciences",
         year = "1781")

bibentry(bibtype = "Article",
         key = "Bouyssou:1992",
         title = "Ranking Methods Based on Valued Preference Relations: A Characterization of the Net Flow Method",
         Volume = "60",
         .issn = "0377-2217",
         doi = "10.1016/0377-2217(92)90333-5",
         number = "1",
         journal = "European Journal of Operational Research",
         publisher = "Elsevier BV",
         author = person(given = "Denis",
                         family = "Bouyssou"),
         year = "1992",
         month = "jul",
         pages = "61--67")

bibentry(bibtype = "Article",
         key = "Clark:1990",
         title = "A Folk Meta-theorem in the Foundations of Utility Theory",
         volume = "19",
         .issn = "0165-4896",
         doi = "10.1016/0165-4896(90)90065-f",
         number = "3",
         journal = "Mathematical Social Sciences",
         publisher = "Elsevier BV",
         author = person(given = c("Stephen", "A."),
                         family = "Clark"),
         year = "1990",
         month = "jun",
         pages = "253--267")

bibentry(bibtype = "Article",
         key = "Codd:1970",
         title = "A Relational Model of Data for Large Shared Data Banks",
         volume = "13",
         .issn = "1557-7317",
         doi = "10.1145/362384.362685",
         number = "6",
         journal = "Communications of the ACM",
         publisher = "Association for Computing Machinery (ACM)",
         author = person(given = c("E.", "F."),
                         family = "Codd"),
         year = "1970",
         month = "jun",
         pages = "377--387")

bibentry(bibtype = "Misc",
         key = "de_Condorcet:1785",
         author = person(given = c("M.", "J.", "A."),
                         family = "de Condorcet"),
         title = "Essai sur l'application de l'analyse {\\`a} la probabilit{\\'e} des d{\\'e}cisions rendues {\\`a} la pluralit{\\'e} des voix",
         year = "1785",
         note = "Paris")

bibentry(bibtype = "Book",
         key = "Cook+Kress:1992",
         author = c(person(given = c("Wade", "D."),
                           family = "Cook"),
                    person(given = "Moshe",
                           family = "Kress")),
         title = "Ordinal information and preference structures: decision models and applications",
         publisher = "Prentice-Hall",
         year = "1992",
         address = "New York",
         isbn = "0-13-630120-7")

bibentry(bibtype = "Article",
         key = "Cook+Kress+Seiford:1986",
         title = "Information and Preference in Partial Orders: A Bimatrix Representation",
         volume = "51",
         .issn = "1860-0980",
         doi = "10.1007/bf02293980",
         number = "2",
         journal = "Psychometrika",
         publisher = "Cambridge University Press (CUP)",
         author = c(person(given = c("Wade", "D."),
                           family = "Cook"),
                    person(given = "Moshe",
                           family = "Kress"),
                    person(given = c("Lawrence", "M."),
                           family = "Seiford")),
         year = "1986",
         month = "jun",
         pages = "197--207")

bibentry(bibtype = "Article",
         key = "Cook+Seiford:1978",
         title = "Priority Ranking and Consensus Formation",
         volume = "24",
         .issn = "1526-5501",
         doi = "10.1287/mnsc.24.16.1721",
         number = "16",
         journal = "Management Science",
         publisher = "Institute for Operations Research and the Management Sciences (INFORMS)",
         author = c(person(given = c("Wade", "D."),
                           family = "Cook"),
                    person(given = c("Lawrence", "M."),
                           family = "Seiford")),
         year = "1978",
         month = "dec",
         pages = "1721--1732")

bibentry(bibtype = "Unpublished",
         key = "Copeland:1951",
         author = person(given = c("A.", "H."),
                         family = "Copeland"),
         title = "A Reasonable Social Welfare Function",
         note = "Notes from a seminar on applications of mathematics to the social sciences. University of Michigan",
         year = "1951")

bibentry(bibtype = "Book",
         key = "Diaconis:1988",
         author = person(given = "Persi",
                         family = "Diaconis"),
         title = "Group Representations in Probability and Statistics",
         year = "1988",
         pages = "198",
         publisher = "Institute of Mathematical Statistics",
         isbn = "0-940600-14-5",
         cisid = "105907",
         volume = "11",
         series = "{IMS} Lecture Notes--Monograph Series",
         address = "Hayward, CA",
         url = "https://projecteuclid.org/euclid.lnms/1215467407")

bibentry(bibtype = "TechReport",
         key = "Emond+Mason:2000",
         author = c(person(given = c("Edward", "J."),
                           family = "Emond"),
                    person(given = c("David", "W."),
                           family = "Mason")),
         title = "A New Technique for High Level Decision Support",
         institution = "Operational Research Division, Department of National Defence, Canada",
         year = "2000",
         number = "ORD Project Report PR2000/13",
         .url = "https://cradpdf.drdc-rddc.gc.ca/PDFS/zbc84/p513851.pdf")

bibentry(bibtype = "Book",
         key = "Fishburn:1972",
         author = person(given = c("Peter", "C."),
                         family = "Fishburn"),
         title = "Mathematics of Decision Theory",
         publisher = "De Gruyter",
         year = "1972",
         volume = "3",
         series = "Methods and Models in the Social Sciences")

bibentry(bibtype = "Book",
         key = "Fodor+Roubens:1994",
         author = c(person(given = c("János", "C."),
                           family = "Fodor"),
                    person(given = c("Marc", "R."),
                           family = "Roubens")),
         title = "Fuzzy Preference Modelling and Multicriteria Decision Support",
         publisher = "Springer Dordrecht",
         year = "1994",
         volume = "14",
         series = "Theory and Decision Library D:",
         doi = "10.1007/978-94-017-1648-2")

bibentry(bibtype = "Article",
         key = "Gaul+Schader:1988",
         title = "Clusterwise Aggregation of Relations",
         volume = "4",
         .issn = "1099-0747",
         doi = "10.1002/asm.3150040406",
         number = "4",
         journal = "Applied Stochastic Models and Data Analysis",
         publisher = "Wiley",
         author = c(person(given = "Wolfgang",
                           family = "Gaul"),
                    person(given = "Martin",
                           family = "Schader")),
         year = "1988",
         month = "dec",
         pages = "273--282")

bibentry(bibtype = "InProceedings",
         key = "Hornik+Meyer:2007",
         author = c(person(given = "Kurt",
                           family = "Hornik",
                           comment = c(ORCID = "0000-0003-4198-9911")),
                    person(given = "David",
                           family = "Meyer",
                           comment = c(ORCID = "0000-0002-5196-3048"))),
         title = "Deriving Consensus Rankings from Benchmarking Experiments",
         year = "2007",
         editor = c(person(given = "R.",
                           family = "Decker"),
                    person(given = "H.-J.",
                           family = "Lenz")),
         publisher = "Springer-Verlag",
         booktitle = "Advances in Data Analysis (Proceedings of the 30th Annual Conference of the Gesellschaft f{\\\"u}r Klassifikation e.V., Freie Universit\\\"at Berlin, March 8--10, 2006",
         pages = "163--170",
         series = "Studies in Classification, Data Analysis, and Knowledge Organization")

bibentry(bibtype = "Article",
         key = "Jabeur+Martel+Khélifa:2004",
         title = "A Distance-Based Collective Preorder Integrating the Relative Importance of the Group’s Members",
         volume = "13",
         .issn = "1572-9907",
         doi = "10.1023/b:grup.0000042894.00775.75",
         number = "4",
         journal = "Group Decision and Negotiation",
         publisher = "Springer Science and Business Media LLC",
         author = c(person(given = "Khaled",
                           family = "Jabeur"),
                    person(given = "Jean-Marc",
                           family = "Martel"),
                    person(given = c("Slim", "Ben"),
                           family = "Khélifa")),
         year = "2004",
         month = "jul",
         pages = "327--349")

bibentry(bibtype = "InBook",
         key = "Kemeny+Snell:1962",
         author = c(person(given = c("John", "G."),
                           family = "Kemeny"),
                    person(given = c("J.", "Laurie"),
                           family = "Snell")),
         title = "Mathematical Models in the Social Sciences",
         chapter = "Preference Rankings: An Axiomatic Approach",
         publisher = "MIT Press",
         year = "1962",
         address = "Cambridge")

bibentry(bibtype = "Article",
         key = "Kendall:1955",
         title = "Further Contributions to the Theory of Paired Comparisons",
         volume = "11",
         .issn = "0006-341X",
         doi = "10.2307/3001479",
         number = "1",
         journal = "Biometrics",
         publisher = "JSTOR",
         author = person(given = c("M.", "G."),
                         family = "Kendall"),
         year = "1955",
         month = "mar",
         pages = "43")

bibentry(bibtype = "InProceedings",
         key = "La_Poutré+van_Leeuwen:1988",
         author = c(person(given = c("J.", "A."),
                           family = "La Poutré"),
                    person(given = "J.",
                           family = c("van", "Leeuwen"))),
         editor = c(person(given = "Herbert",
                           family = "Göttler"),
                    person(given = "Hana-Jürgen",
                           family = "Schneider")),
         title = "Maintenance of transitive closures and transitive reductions of graphs",
         booktitle = "Graph-Theoretic Concepts in Computer Science",
         year = "1988",
         publisher = "Springer Berlin Heidelberg",
         address = "Berlin, Heidelberg",
         pages = "106--120",
         isbn = "978-3-540-39264-4",
         doi = "10.1007/3-540-19422-3_9")

bibentry(bibtype = "Article",
         key = "Marcotorchino+Michaud:1982",
         author = c(person(given = "F.",
                           family = "Marcotorchino"),
                    person(given = "P.",
                           family = "Michaud")),
         title = "Agr{\\'e}gation de similarit{\\'e}s en classification automatique",
         journal = "Revue de Statistique Appliqu{\\'e}e",
         year = "1982",
         volume = "30",
         number = "2",
         pages = "21--44",
         url = "https://eudml.org/doc/106132")

bibentry(bibtype = "Article",
         key = "Meyer+Leisch+Hornik:2003",
         title = "The Support Vector Machine under Test",
         volume = "55",
         .issn = "0925-2312",
         doi = "10.1016/s0925-2312(03)00431-4",
         number = "1--2",
         journal = "Neurocomputing",
         publisher = "Elsevier BV",
         author = c(person(given = "David",
                           family = "Meyer",
                           comment = c(ORCID = "0000-0002-5196-3048")),
                    person(given = "Friedrich",
                           family = "Leisch"),
                    person(given = "Kurt",
                           family = "Hornik",
                           comment = c(ORCID = "0000-0003-4198-9911"))),
         year = "2003",
         month = "sep",
         pages = "169--186")

bibentry(bibtype = "Article",
         key = "Ovchinnikov:1991",
         title = "Similarity Relations, Fuzzy Partitions, and Fuzzy Orderings",
         volume = "40",
         .issn = "0165-0114",
         doi = "10.1016/0165-0114(91)90048-u",
         number = "1",
         journal = "Fuzzy Sets and Systems",
         publisher = "Elsevier BV",
         author = person(given = "Sergei",
                         family = "Ovchinnikov"),
         year = "1991",
         month = "mar",
         pages = "107--126")

bibentry(bibtype = "Article",
         key = "Regenwetter+Rykhlevskaia:2004",
         title = "On the (Numerical) Ranking Associated with any Finite Binary Relation",
         volume = "48",
         .issn = "0022-2496",
         doi = "10.1016/j.jmp.2004.03.003",
         number = "4",
         journal = "Journal of Mathematical Psychology",
         publisher = "Elsevier BV",
         author = c(person(given = "Michel",
                           family = "Regenwetter"),
                    person(given = "Elena",
                           family = "Rykhlevskaia")),
         year = "2004",
         month = "aug",
         pages = "239--246")

bibentry(bibtype = "Article",
         key = "Régnier:1965",
         author = person(given = "S.",
                         family = "Régnier"),
         title = "Sur quelques aspects math{\\'e}matiques des probl{\\`e}mes de classification automatique",
         journal = "ICC Bulletin",
         year = "1965",
         volume = "4",
         pages = "175--191")

bibentry(bibtype = "Book",
         key = "Varian:2002",
         author = person(given = c("Hal", "E."),
                         family = "Varian"),
         title = "Intermediate Microeconomics: A Modern Approach",
         publisher = "W. W. Morton \\& Company",
         year = "2002",
         edition = "Sixth")

bibentry(bibtype = "InCollection",
         key = "Vescia:1985",
         author = person(given = "G.",
                         family = "Vescia"),
         title = "Descriptive Classification of Cetacea: Whales, Porpoises, and Dolphins",
         booktitle = "Data analysis in real life environment: ins and outs of solving problems",
         publisher = "Elsevier Science Publishers B.V.",
         year = "1985",
         editor = c(person(given = c("J.", "F."),
                           family = "Marcotorchino"),
                    person(given = c("J.", "M."),
                           family = "Proth"),
                    person(given = "J.",
                           family = "Janssen")),
         address = "Amsterdam, The Netherlands")

bibentry(bibtype = "Article",
         key = "Warshall:1962",
         title = "A Theorem on Boolean Matrices",
         volume = "9",
         .issn = "1557-735X",
         doi = "10.1145/321105.321107",
         number = "1",
         journal = "Journal of the ACM",
         publisher = "Association for Computing Machinery (ACM)",
         author = person(given = "Stephen",
                         family = "Warshall"),
         year = "1962",
         month = "jan",
         pages = "11--12")

bibentry(bibtype = "PhdThesis",
         key = "Wei:1952",
         author = person(given = "Teh-Hsing",
                         family = "Wei"),
         title = "Algebraic foundations of ranking theory",
         school = "University of Cambridge",
         year = "1952",
         url = "https://www.repository.cam.ac.uk/handle/1810/250988")
